### ISSUE TITLE
Biomatrix Backup needs to be changed

### ISSUE THREAD

**Issue by metaltrav** [jeremylarner/keyteki#208]
I wish you would reconsider your standing interpretation of Biomatrix Backup and going with what Richard Garfield himself has stated is "an error." There is overwhelming community support to correct this obvious oversight on Fantasy Flight's part. 

The current ruling makes the card utterly worthless.

**Comment by samlehman** [comment]
I vote that the crucible follows the rules as per the rulebook (w/ FAQ) than implementing house rules.

**Comment by ejlertson** [comment]
Horrible idea. As long as the ruling is what it is, thecrucible should follow that.

And you are wrong. It gives you an Æmber and you can then us the creature to fight something that you will kill and which will kill you, and instead of having the creature go on the discard it goes to your archive.
It may not be as strong as you wish but it is far from worthless

**Comment by metaltrav** [comment]
A horrible idea that has overwhelming support from players and the game
creator... Right.

**Comment by BrianMJWood** [comment]
Aside from the fact that I see zero "overwhelming support" for this change, Richard Garfield stated in his BGG posts that while it was an error, he deferred to FFG to make the official ruling.

FFG made their specific ruling for the card clear in the rulebook errata.

Not using the official rules and instead building an online version of the game that deliberately omits whatever rules displease you would be ridiculous.

**Comment by metaltrav** [comment]
Can I set aside the legitimate argument we are having for a moment to point
out that you are being a real jerk to me. My first message urged you to
reconsider a contested ruling. Not once did I criticize you or the
excellent site you have built. Yet you have repeatedly dismissed my points
as selfish whims.

I still back my side of this argument because I don't see this as a simple
houserule--it's different, an admitted defect. I hate to see an error
persist when it is acknowlwdged to be an error. Like a fly in the ointment,
so to speak.

That being said, if you want the site to reflect RAW, I get it. There are
good reasons I can think of for this. (Though I still think my reasons are
stronger.) It's just what you think the site should be, to wait for this
very young game to evolve on its own. I get that.

This hobby is always going to produce debates and strong opinions. And that
has unfortunately created some toxicity. I'm not attacking you, dude. So
quit belittling me.


-Travis

**Comment by BrianMJWood** [comment]
I didn't create the site, I'm just a fan like anyone else who wants it to be as good as possible. That includes playing by the rules in the rulebook.

Your entire claim seems to be around what Richard wrote on BGG. "This is an error". Yep. He was also clear that his post was not a rules errata, nor would anything change unless FFG says so. That was in August.

In November, FFG updated the rulebook with the Biomatrix Backup errata, confirming what Richard said in his post on BGG: Biomatrix would be played as written. That's the call that was made. It's no longer a contested ruling, because it was specifically acknowledged in the errata. 

Given all that, I don't see any reason to force people online to play with rules that directly contradict the official rulebook.

**Comment by metaltrav** [comment]
I legitimately thought I had sent a message to the site admins. I didn't mean to post this in a forum.

**Comment by BrianMJWood** [comment]
Well, you did both.

As per the heading, this forum is used by the admins to "track bugs, enhancements, and ideas. You can submit new bugs, requests, or join the discussion." 

So you if you want the admins to change, add or update something, this is the correct place to it.

**Comment by samlehman** [comment]
So as per the updated rulebook, biomatrix now reads “This creature gains,”Destroyed: Put this creature into its owner’s archives.”

https://kop-cdn.keyforgegame.com/filer_public/30/03/30032847-fa82-46a3-a28b-984efc5a91ca/keyforge_rulebook_v8-compressed.pdf
