### ISSUE TITLE
Lash of Broken Dreams is...broken?

### ISSUE THREAD

**Issue by gardenFiend138** [jeremylarner/keyteki#409]
<img width="1440" alt="Screen Shot 2019-08-01 at 6 52 17 PM" src="https://user-images.githubusercontent.com/26235016/62338516-b74a5080-b48d-11e9-9aa3-190f1e0c810b.png">
<img width="1440" alt="Screen Shot 2019-08-01 at 6 52 39 PM" src="https://user-images.githubusercontent.com/26235016/62338521-bb766e00-b48d-11e9-8fe1-8a17493b5e3a.png">

 See screenshots above -- Lash of Broken Dreams was played when opponent had 8 and I had 2 aember. Throughout turn, got to 6 aember myself, but opponent was still able to forge key on next turn. Lost the game because of it. Excellent endeavor though, love this online play!

**Comment by Achocholacek** [comment]
Hi @gardenFiend138 - The Lash is an artifact, and its "Action:" ability must be used in order to increase your opponent's key cost by 3. In this case, you played it (but did not use it, as it was freshly played), finished your turn, and your opponent was able to forge.

All is working as expected! :)
