### ISSUE TITLE
Vigor

### ISSUE THREAD

**Issue by jpraet** [jeremylarner/keyteki#67]
Vigor (Play: Heal up to 3 damage from a creature. If you healed 3 damage, gain 1 amber) forced me to heal my opponent's creature. I had creatures out but none of them had any damage. I guess it's correct that the app only allows me to target creatures with damage on them. But it says "up to 3 damage", so I should be able to choose to heal 0 damage, right?

**Comment by 3pw00d** [comment]
Hi, 

i think it's correct to select opponent's creature when you have no creature to heal, but i rejoin you on the amount to heal howevere i think the minimum is one damage to heal otherwise the word "heal" is not performed.

I am adding my two cents on your thread cause i saw another bug with that card: When you heal a creature (yours or theirs) of 3 damage, you don't gain 1 aember. Which is, from the cad, incorrect.

Thank you
Regards

**Comment by jpraet** [comment]
> i think the minimum is one damage to heal otherwise the word "heal" is not performed.

I see your point but not sure I agree with that. What about cards like Nocturnal Maneuver (exhaust up to 3 creatures) or Creeping Oblivion (purge up to 2 cards from a discard pile). Would you say that on those cards you also need to do 1 minimum then if you can, as otherwise you wouldn't have performed the words "exhaust" or "purge"? I take up to 3 as giving you the choice of 0, 1, 2 or 3.

But I could be wrong, you never know with this game ;-)

**Comment by 3pw00d** [comment]
From the few card games that i play, the wording was always "key". So if it can't happen, you can't do it. So for your examples, i will do the same as for healing. But there is a slight change that i might be wrong :)

**Comment by jeremylarner** [comment]
This should be fixed now
